name: smart_cv
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  intl: ^0.18.0
  provider: ^6.1.2
  flutter_localized_locales: ^2.0.5
  http: ^1.2.1
  shared_preferences: ^2.2.3

  # RENDER HTML TEMPLATE 
  flutter_widget_from_html: ^0.15.0  
  url_launcher: ^6.2.6
  open_filex: ^4.4.0

  #DRAGABLE APPBAR 
  draggable_home: ^1.0.5
  window_manager: ^0.3.8

  flutter_test: 
    sdk: flutter
  multi_dropdown: ^2.1.4
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/home/

  fonts: 
    - family: Inria Serif
      fonts: 
        - asset: assets/fonts/InriaSerifBold.ttf
          weight: 700
        - asset: assets/fonts/InriaSerifRegular.ttf
          weight: 400
        - asset: assets/fonts/InriaSerifBoldItalic.ttf
          weight: 700
